[project]
name = "typer-task"
version = "0.1.0"
description = "A simple CLI Task Manager built with Typer"
authors = [{ name = "Ziam Hassan" }]
requires-python = ">=3.8"

dependencies = [
    "pytest>=8.4.2",
    "typer",
]

[tool.uv]
# optional, helps uv manage this environment cleanly
